version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: musicbrainz
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d musicbrainz"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Database initialization service (runs once)
  db-init:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.init
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/musicbrainz
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"  # Only run once

  artist-service:
    build: 
      context: .
      dockerfile: dockerfiles/Dockerfile.artist
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/musicbrainz
    depends_on:
      db-init:
        condition: service_completed_successfully

  album-service:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.album
    ports:
      - "8002:8002"
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/musicbrainz
    depends_on:
      db-init:
        condition: service_completed_successfully

  recommendation-service:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.recommendation
    ports:
      - "8003:8003"
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/musicbrainz
    depends_on:
      db-init:
        condition: service_completed_successfully

  api-gateway:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.gateway
    ports:
      - "8000:8000"
    environment:
      ARTIST_SERVICE_URL: http://artist-service:8001
      ALBUM_SERVICE_URL: http://album-service:8002
      RECOMMENDATION_SERVICE_URL: http://recommendation-service:8003
    depends_on:
      - artist-service
      - album-service
      - recommendation-service

volumes:
  postgres_data: